services:
  main_app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main_app
    ports:
    - "8000:8000"
    command: "python -m src.main"
    env_file:
    - ../.env
    networks:
    - backend

networks:
  backend:
    driver: bridge
